/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vue;

import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JComboBox;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.AbstractDocument;
import javax.swing.text.DocumentFilter.FilterBypass; // Add this line to specifically import FilterBypass
import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import modele.dao.DaoCategorie;
import modele.dao.DaoService;
import modele.dao.DaoSalarie;
import modele.metier.Categorie;
import modele.metier.Salarie;
import modele.metier.Service;

/**
 *
 * @author brieu
 */
public class JDialogAjouterSalarie extends javax.swing.JDialog {

    // les modèles 
    private DefaultComboBoxModel modeleJComboLesCategories;
    private DefaultComboBoxModel modeleJComboLesServices;

    /**
     * Creates new form JDialogAjouterSalarie
     */
    public JDialogAjouterSalarie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(350, 100);

        //Définitions des différents ComboBoxModel
        modeleJComboLesCategories = new DefaultComboBoxModel();
        jComboBoxCat.setModel(modeleJComboLesCategories);

        modeleJComboLesServices = new DefaultComboBoxModel();
        jComboBoxService.setModel(modeleJComboLesServices);

        // Ajouter un filtre de document pour restreindre l'entrée aux entiers pour le champ "Code"
        ((AbstractDocument) jTextFieldCode.getDocument()).setDocumentFilter(new IntFilter());

        // Ajouter un filtre de document pour restreindre l'entrée aux entiers pour le champ "Nombre d'enfants"
        ((AbstractDocument) jTextFieldNbEnfant.getDocument()).setDocumentFilter(new IntFilter());

        // Ajouter un filtre de document pour restreindre l'entrée aux entiers pour le champ "Nombre d'enfants"
        ((AbstractDocument) jTextFieldTauxHorr.getDocument()).setDocumentFilter(new IntFilter());
        
        try {
            ArrayList<Service> lesServices = DaoService.getAll();
            ArrayList<Categorie> lesCategories = DaoCategorie.getAll();
            remplirJComboBoxServices(lesServices);
            remplirJComboBoxCategories(lesCategories);
        } catch (SQLException ex) {
            System.out.println("Erreur : " + ex.getMessage());
        } catch (IOException ex) {
            System.out.println("Erreur : " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabelTitre = new javax.swing.JLabel();
        jPanelInfosSalariés = new javax.swing.JPanel();
        jTextTitreCode = new javax.swing.JLabel();
        jLabelTitreNom = new javax.swing.JLabel();
        jLabelTitrePrenom = new javax.swing.JLabel();
        jLabelTitreDateNaiss = new javax.swing.JLabel();
        jLabelTitreDateEmbauche = new javax.swing.JLabel();
        jLabelTitreFonction = new javax.swing.JLabel();
        jLabelTitreTauxHoraire = new javax.swing.JLabel();
        jLabelTitreSituationFamiliale = new javax.swing.JLabel();
        jLabelTitreNbrEnfants = new javax.swing.JLabel();
        jLabelTitreCat = new javax.swing.JLabel();
        jLabelTitreService = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jDateChooserDateNaiss = new com.toedter.calendar.JDateChooser();
        jDateChooserDateEmbauche = new com.toedter.calendar.JDateChooser();
        jComboBoxCat = new javax.swing.JComboBox<>();
        jTextFieldTauxHorr = new javax.swing.JTextField();
        jTextFieldSitFamiliale = new javax.swing.JTextField();
        jTextFieldNbEnfant = new javax.swing.JTextField();
        jLabelTitreCode1 = new javax.swing.JLabel();
        jComboBoxService = new javax.swing.JComboBox<>();
        jTextFieldFonction = new javax.swing.JTextField();
        jLabelSousTitre = new javax.swing.JLabel();
        jButtonValider = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitre.setText("Ajouter un salarié");

        jPanelInfosSalariés.setBackground(new java.awt.Color(255, 255, 255));

        jTextTitreCode.setText("Code :");

        jLabelTitreNom.setText("Nom :");

        jLabelTitrePrenom.setText("Prenom :");

        jLabelTitreDateNaiss.setText("Date de naissance :");

        jLabelTitreDateEmbauche.setText("Date d'embauche :");

        jLabelTitreFonction.setText("Fonction :");

        jLabelTitreTauxHoraire.setText("Taux horaire (en h) :");

        jLabelTitreSituationFamiliale.setText("Situation familiale :");

        jLabelTitreNbrEnfants.setText("Nombre d'enfants :");

        jLabelTitreCat.setText("Catégorie :");

        jLabelTitreService.setText("Service :");

        jTextFieldCode.setBackground(new java.awt.Color(245, 245, 245));
        jTextFieldCode.setToolTipText("Code du salarié (Ex : 01)");
        jTextFieldCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeActionPerformed(evt);
            }
        });

        jTextFieldNom.setBackground(new java.awt.Color(245, 245, 245));
        jTextFieldNom.setToolTipText("Nom du salarié (Ex : Jean)");
        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });

        jTextFieldPrenom.setBackground(new java.awt.Color(245, 245, 245));
        jTextFieldPrenom.setToolTipText("Prénom du salarié (Ex : Dupont)");
        jTextFieldPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomActionPerformed(evt);
            }
        });

        jDateChooserDateNaiss.setToolTipText("Date de naissance du salarié");

        jDateChooserDateEmbauche.setToolTipText("Date d'embauche du salarié");

        jComboBoxCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCat.setToolTipText("Catégorie du salarié");

        jTextFieldTauxHorr.setBackground(new java.awt.Color(245, 245, 245));
        jTextFieldTauxHorr.setToolTipText("Taux horaire du salarié (Ex : 32)");
        jTextFieldTauxHorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTauxHorrActionPerformed(evt);
            }
        });

        jTextFieldSitFamiliale.setBackground(new java.awt.Color(245, 245, 245));
        jTextFieldSitFamiliale.setToolTipText("Situation familiale du salarié (Ex : Marié.e)");
        jTextFieldSitFamiliale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSitFamilialeActionPerformed(evt);
            }
        });

        jTextFieldNbEnfant.setBackground(new java.awt.Color(245, 245, 245));
        jTextFieldNbEnfant.setToolTipText("Nombre d'enfant du salarié (Ex : 1)");
        jTextFieldNbEnfant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNbEnfantActionPerformed(evt);
            }
        });

        jLabelTitreCode1.setText("S");

        jComboBoxService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxService.setToolTipText("Service du salarié");

        jTextFieldFonction.setBackground(new java.awt.Color(245, 245, 245));
        jTextFieldFonction.setToolTipText("Fonction du salarié (Ex : Développeur)");
        jTextFieldFonction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFonctionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfosSalariésLayout = new javax.swing.GroupLayout(jPanelInfosSalariés);
        jPanelInfosSalariés.setLayout(jPanelInfosSalariésLayout);
        jPanelInfosSalariésLayout.setHorizontalGroup(
            jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfosSalariésLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfosSalariésLayout.createSequentialGroup()
                        .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextTitreCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(jLabelTitreNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelTitrePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInfosSalariésLayout.createSequentialGroup()
                                .addComponent(jLabelTitreCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldNom)
                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanelInfosSalariésLayout.createSequentialGroup()
                        .addComponent(jLabelTitreDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserDateNaiss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInfosSalariésLayout.createSequentialGroup()
                        .addComponent(jLabelTitreDateEmbauche, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jDateChooserDateEmbauche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInfosSalariésLayout.createSequentialGroup()
                        .addComponent(jLabelTitreService, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxService, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInfosSalariésLayout.createSequentialGroup()
                        .addComponent(jLabelTitreFonction, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTextFieldFonction))
                    .addGroup(jPanelInfosSalariésLayout.createSequentialGroup()
                        .addComponent(jLabelTitreTauxHoraire, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTextFieldTauxHorr))
                    .addGroup(jPanelInfosSalariésLayout.createSequentialGroup()
                        .addComponent(jLabelTitreSituationFamiliale, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSitFamiliale))
                    .addGroup(jPanelInfosSalariésLayout.createSequentialGroup()
                        .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitreCat, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTitreNbrEnfants, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNbEnfant)
                            .addComponent(jComboBoxCat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelInfosSalariésLayout.setVerticalGroup(
            jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfosSalariésLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTitreCode)
                    .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitreCode1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitreNom)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitrePrenom)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitreDateNaiss)
                    .addComponent(jDateChooserDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitreDateEmbauche)
                    .addComponent(jDateChooserDateEmbauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitreFonction)
                    .addComponent(jTextFieldFonction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfosSalariésLayout.createSequentialGroup()
                        .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitreTauxHoraire)
                            .addComponent(jTextFieldTauxHorr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitreSituationFamiliale)
                            .addComponent(jTextFieldSitFamiliale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitreNbrEnfants)
                            .addComponent(jTextFieldNbEnfant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTitreCat)
                            .addComponent(jComboBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfosSalariésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTitreService, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelSousTitre.setText("Informations :  ");

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jPanelInfosSalariés, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelSousTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButtonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSousTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelInfosSalariés, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButtonValider)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonRetour)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        // La classe IntFilter pour restreindre l'entrée aux entiers
     class IntFilter extends DocumentFilter {

         @Override
         public void insertString(FilterBypass bypass, int offset, String string, AttributeSet attr) throws BadLocationException {
             StringBuilder stringBuilder = new StringBuilder();
             stringBuilder.append(bypass.getDocument().getText(0, bypass.getDocument().getLength()));
             stringBuilder.insert(offset, string);

             if (isValid(stringBuilder.toString())) {
                 super.insertString(bypass, offset, string, attr);
             }
         }

         @Override
         public void replace(FilterBypass bypass, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
             StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.append(bypass.getDocument().getText(0, bypass.getDocument().getLength()));
            stringBuilder.replace(offset, offset + length, text);

            if (isValid(stringBuilder.toString())) {
                super.replace(bypass, offset, length, text, attrs);
            }
        }

        private boolean isValid(String text) {
            if (text.isEmpty()) {
                return true;
            }
            try {
                Integer.parseInt(text);
                return true;
            } catch (NumberFormatException e) {
                return false;
            }
        }
    }

    private void jTextFieldCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodeActionPerformed

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jTextFieldPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomActionPerformed

    private void jTextFieldTauxHorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTauxHorrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTauxHorrActionPerformed

    private void jTextFieldSitFamilialeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSitFamilialeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSitFamilialeActionPerformed

    private void jTextFieldNbEnfantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNbEnfantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNbEnfantActionPerformed

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jTextFieldFonctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFonctionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFonctionActionPerformed

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        String codeSalarie = "S" + jTextFieldCode.getText();
        String nomSalarie = jTextFieldNom.getText();
        String prenomSalarie = jTextFieldPrenom.getText();
        Date dateNaissSalarie = jDateChooserDateNaiss.getDate();
        Date dateEmbaucheSalarie = jDateChooserDateEmbauche.getDate();
        String fonctionSalarie = jTextFieldFonction.getText();
        double tauxHoraireSalarie = Double.parseDouble(jTextFieldTauxHorr.getText());
        String situationFamilialeSalarie = jTextFieldSitFamiliale.getText();
        int nbEnfantSalarie = Integer.parseInt(jTextFieldNbEnfant.getText());
        Categorie catSalarie = (Categorie) jComboBoxCat.getSelectedItem();
        Service serviceSalarie = (Service) jComboBoxService.getSelectedItem();
        
        Salarie nouveauSalarie = new Salarie(codeSalarie, nomSalarie, prenomSalarie, dateNaissSalarie, dateEmbaucheSalarie, fonctionSalarie, tauxHoraireSalarie, situationFamilialeSalarie, nbEnfantSalarie, serviceSalarie, catSalarie);
        
        try {
            //On appelle la fonction DaoSalarie.AjouterSalarie qui va permettre d'ajouter le salarie à la base de données.
            DaoSalarie.AjouterSalarie(nouveauSalarie);
            System.out.println("Les informations ont été mis à jour.");
            
        } catch (SQLException ex) {
            System.out.println("Erreur : "+ ex.getMessage());
        }
        
        this.dispose();
    }//GEN-LAST:event_jButtonValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAjouterSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAjouterSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAjouterSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAjouterSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogAjouterSalarie dialog = new JDialogAjouterSalarie(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    //SERVICE
        public void remplirJComboBoxServices(List<Service> lesServices) throws SQLException, IOException {
        modeleJComboLesServices.removeAllElements();
        // Options suivantes : une par service
        for (Service unService : lesServices) {
            modeleJComboLesServices.addElement(unService);
        }
    }
    //CATEGORIE
        public void remplirJComboBoxCategories(List<Categorie> lesCategories) throws SQLException, IOException {
        modeleJComboLesCategories.removeAllElements();
        // Options suivantes : une par service
        for (Categorie uneCategorie : lesCategories) {
            modeleJComboLesCategories.addElement(uneCategorie);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonValider;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBoxCat;
    private javax.swing.JComboBox<String> jComboBoxService;
    private com.toedter.calendar.JDateChooser jDateChooserDateEmbauche;
    private com.toedter.calendar.JDateChooser jDateChooserDateNaiss;
    private javax.swing.JLabel jLabelSousTitre;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JLabel jLabelTitreCat;
    private javax.swing.JLabel jLabelTitreCode1;
    private javax.swing.JLabel jLabelTitreDateEmbauche;
    private javax.swing.JLabel jLabelTitreDateNaiss;
    private javax.swing.JLabel jLabelTitreFonction;
    private javax.swing.JLabel jLabelTitreNbrEnfants;
    private javax.swing.JLabel jLabelTitreNom;
    private javax.swing.JLabel jLabelTitrePrenom;
    private javax.swing.JLabel jLabelTitreService;
    private javax.swing.JLabel jLabelTitreSituationFamiliale;
    private javax.swing.JLabel jLabelTitreTauxHoraire;
    private javax.swing.JPanel jPanelInfosSalariés;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldFonction;
    private javax.swing.JTextField jTextFieldNbEnfant;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldSitFamiliale;
    private javax.swing.JTextField jTextFieldTauxHorr;
    private javax.swing.JLabel jTextTitreCode;
    // End of variables declaration//GEN-END:variables
}
