/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vue;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static modele.dao.DaoSalarie.*;
import static modele.dao.DaoSalarie.deleteSalarie;
import javax.swing.JOptionPane;
import lanceur.Main;
import modele.metier.Salarie;
/**
 *
 * @author croua
 */
public class JDialogModifSalarie extends javax.swing.JDialog {

    /**
     * Méthode pour mettre à jour les champs de texte avec les informations du salarié.
     * @param salarie
     */
    public void setSalariesInfo(Salarie salarie) {
        // Remplir les champs de texte avec les informations du salarié
        jTextFieldCode.setText(salarie.getCode());
        jTextFieldNom.setText(salarie.getNom());
        jTextFieldPrenom.setText(salarie.getPrenom());
        jTextFieldDateNaissance.setText(salarie.getDateNaiss().toString());
        jTextFieldDateEmbauche.setText(salarie.getDateEmbauche().toString());
        jTextFieldFonction.setText(salarie.getFonction());
        jTextFieldTauxHoraire.setText(String.valueOf(salarie.getTauxHoraire()));
        jTextFieldSituationFamiliale.setText(salarie.getSituationFamiliale());
        jTextFieldNombreEnfants.setText(String.valueOf(salarie.getNbrEnfants()));

        // Vérifier si le service du salarié est non null avant de récupérer le code du service
        if (salarie.getService() != null) {
            jTextFieldCodeService.setText(String.valueOf(salarie.getService().getCode()));
        } else {
            jTextFieldCodeService.setText("");
        }

        // Vérifier si la catégorie du salarié est non null avant de récupérer le numéro de catégorie
        if (salarie.getCategorie() != null) {
            jTextFieldNumCathegorie.setText(salarie.getCategorie().getCode());
        } else {
            jTextFieldNumCathegorie.setText("");
        }
    }

    private JFrameListeSalaries parentFrame;

    public void setParentFrame(JFrameListeSalaries parentFrame) {
        this.parentFrame = parentFrame;
    }

    /**
     * Creates new form JDialogAll
     */
    public JDialogModifSalarie(java.awt.Frame parent, boolean modal) {
            super(parent, modal);
            initComponents();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabelCode = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelDateNaiss = new javax.swing.JLabel();
        jLabelDateEmb = new javax.swing.JLabel();
        jLabelFonct = new javax.swing.JLabel();
        jLabelTauxHorr = new javax.swing.JLabel();
        jLabelSituFami = new javax.swing.JLabel();
        jLabelNbEnfant = new javax.swing.JLabel();
        jLabelNbCath = new javax.swing.JLabel();
        jLabelCodeServ = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldFonction = new javax.swing.JTextField();
        jTextFieldTauxHoraire = new javax.swing.JTextField();
        jTextFieldNombreEnfants = new javax.swing.JTextField();
        jButtonModifAjout1 = new javax.swing.JButton();
        jTextFieldDateNaissance = new javax.swing.JTextField();
        jTextFieldDateEmbauche = new javax.swing.JTextField();
        jTextFieldSituationFamiliale = new javax.swing.JTextField();
        jTextFieldNumCathegorie = new javax.swing.JTextField();
        jTextFieldCodeService = new javax.swing.JTextField();
        jButtonValider = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelCode.setText("Code :");

        jLabelNom.setText("Nom :");

        jLabelPrenom.setText("Prénom :");

        jLabelDateNaiss.setText("Date naissance :");

        jLabelDateEmb.setText("Date embauche :");

        jLabelFonct.setText("Fonction :");

        jLabelTauxHorr.setText("Taux horaire :");

        jLabelSituFami.setText("Situation familiale :");

        jLabelNbEnfant.setText("Nombre enfants :");

        jLabelNbCath.setText("Numéro cathegorie :");

        jLabelCodeServ.setText("Code service :");

        jTextFieldCode.setEditable(false);
        jTextFieldCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeActionPerformed(evt);
            }
        });

        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });

        jTextFieldPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomActionPerformed(evt);
            }
        });

        jTextFieldFonction.setText("Chef de projet");
        jTextFieldFonction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFonctionActionPerformed(evt);
            }
        });

        jTextFieldTauxHoraire.setText("32.5");
        jTextFieldTauxHoraire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTauxHoraireActionPerformed(evt);
            }
        });

        jTextFieldNombreEnfants.setText("3");
        jTextFieldNombreEnfants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreEnfantsActionPerformed(evt);
            }
        });

        jButtonModifAjout1.setText("Quitter");
        jButtonModifAjout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifAjout1ActionPerformed(evt);
            }
        });

        jTextFieldDateNaissance.setText("10/03/1995");
        jTextFieldDateNaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateNaissanceActionPerformed(evt);
            }
        });

        jTextFieldDateEmbauche.setText("23/10/2023");
        jTextFieldDateEmbauche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateEmbaucheActionPerformed(evt);
            }
        });

        jTextFieldSituationFamiliale.setText("Marie");
        jTextFieldSituationFamiliale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSituationFamilialeActionPerformed(evt);
            }
        });

        jTextFieldNumCathegorie.setText("E1");
        jTextFieldNumCathegorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumCathegorieActionPerformed(evt);
            }
        });

        jTextFieldCodeService.setText("S01");
        jTextFieldCodeService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeServiceActionPerformed(evt);
            }
        });

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jLabel1.setText("Modification des informations du salarié :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonValider)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModifAjout1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCode, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDateEmb, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFonct, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTauxHorr, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSituFami, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNbEnfant, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNbCath, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCodeServ, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreEnfants, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldTauxHoraire, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldFonction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldDateNaissance, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldDateEmbauche)
                            .addComponent(jTextFieldSituationFamiliale)
                            .addComponent(jTextFieldNumCathegorie)
                            .addComponent(jTextFieldCodeService, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenom))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateNaiss)
                    .addComponent(jTextFieldDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateEmb)
                    .addComponent(jTextFieldDateEmbauche, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFonction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFonct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTauxHoraire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTauxHorr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSituFami)
                    .addComponent(jTextFieldSituationFamiliale, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreEnfants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNbEnfant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbCath)
                    .addComponent(jTextFieldNumCathegorie, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodeServ)
                    .addComponent(jTextFieldCodeService, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifAjout1)
                    .addComponent(jButtonValider))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodeActionPerformed

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jTextFieldPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomActionPerformed

    private void jTextFieldFonctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFonctionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFonctionActionPerformed

    private void jTextFieldTauxHoraireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTauxHoraireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTauxHoraireActionPerformed

    private void jTextFieldNombreEnfantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreEnfantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreEnfantsActionPerformed

    private void jButtonModifAjout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifAjout1ActionPerformed
        this.dispose();
        new JFrameListeSalaries().setVisible(false);
        
        Main.main(new String[]{});
    }//GEN-LAST:event_jButtonModifAjout1ActionPerformed

    private void jButtonModifSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifSuppActionPerformed
             
    }//GEN-LAST:event_jButtonModifSuppActionPerformed
    private void jTextFieldDateNaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateNaissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateNaissanceActionPerformed

    private void jTextFieldDateEmbaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateEmbaucheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateEmbaucheActionPerformed

    private void jTextFieldSituationFamilialeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSituationFamilialeActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSituationFamilialeActionPerformed

    private void jTextFieldNumCathegorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumCathegorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumCathegorieActionPerformed

    private void jTextFieldCodeServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodeServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodeServiceActionPerformed

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        int reponse = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr de vouloir modifier l'utilisateur "+ jTextFieldPrenom.getText() +" "+ jTextFieldNom.getText() +" ? ","Confirmation", JOptionPane.YES_NO_OPTION);
        if (reponse == JOptionPane.YES_OPTION) {
            // Code si Oui
            try {
                // Fermer la fenêtre actuelle
                this.dispose();

                // Supprimer le salarié en utilisant le code saisi dans le champ jTextFieldCode
                deleteSalarie(jTextFieldCode.getText());

                // Afficher la fenêtre JFrameListeSalaries
                // JFrameListeSalaries listeSalariesFrame = new JFrameListeSalaries();
                // listeSalariesFrame.setVisible(true);
                Main.main(new String[]{});
            } catch (Exception ex) {
                System.out.println("Erreur lors de La Suppression du Salarié Demandé : " + ex.getMessage());
            }
        } else {
            // Code si Non
        }
    }//GEN-LAST:event_jButtonValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogModifSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogModifSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogModifSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogModifSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogModifSalarie dialog = new JDialogModifSalarie(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModifAjout1;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelCodeServ;
    private javax.swing.JLabel jLabelDateEmb;
    private javax.swing.JLabel jLabelDateNaiss;
    private javax.swing.JLabel jLabelFonct;
    private javax.swing.JLabel jLabelNbCath;
    private javax.swing.JLabel jLabelNbEnfant;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelSituFami;
    private javax.swing.JLabel jLabelTauxHorr;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldCodeService;
    private javax.swing.JTextField jTextFieldDateEmbauche;
    private javax.swing.JTextField jTextFieldDateNaissance;
    private javax.swing.JTextField jTextFieldFonction;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldNombreEnfants;
    private javax.swing.JTextField jTextFieldNumCathegorie;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldSituationFamiliale;
    private javax.swing.JTextField jTextFieldTauxHoraire;
    // End of variables declaration//GEN-END:variables
}
